// Code generated by goctl. DO NOT EDIT.
// Source: rpc.proto

package server

import (
	"context"

	"github.com/woxQAQ/im-service/internal/rpc/imrpc_user/internal/logic"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_user/internal/svc"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_user/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *pb.UserInfoRequest) (*pb.UserInfoResp, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UserServer) ModifyInfo(ctx context.Context, in *pb.ModifyInfoRequest) (*pb.ModifyInfoResp, error) {
	l := logic.NewModifyInfoLogic(ctx, s.svcCtx)
	return l.ModifyInfo(in)
}
