// Code generated by goctl. DO NOT EDIT.
package types

type MsgData struct {
	MsgId   int64  `json:"msgId"`
	Content string `json:"content"`
}

type ResponseData struct {
	ClientMsgId string `json:"clientMsgId"`
	ServerMsgId string `json:"serverMsgId"`
	SendTime    string `json:"sendTime"`
}

type SendRequest struct {
	SenderId       string  `json:"senderId"`
	ReceiverId     string  `json:"receiverId"`
	SenderPlatform int     `json:"senderPlatform"`
	GroupId        int     `json:"groupId"`
	Content        MsgData `json:"content"`
	ContentType    int     `json:"contentType"`
	SessionType    int     `json:"sessionType"`
	SendTime       int     `json:"sendTime"`
}

type SendResponse struct {
	ErrCode int          `json:"errCode"`
	ErrMsg  string       `json:"errMsg"`
	ErrDlt  string       `json:"errDlt"`
	Data    ResponseData `json:"data"`
}
