// Code generated by goctl. DO NOT EDIT.

package seq

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionSequenceFieldNames          = builder.RawFieldNames(&SessionSequence{})
	sessionSequenceRows                = strings.Join(sessionSequenceFieldNames, ",")
	sessionSequenceRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionSequenceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionSequenceRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionSequenceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSessionSequenceIdPrefix = "cache:sessionSequence:id:"
)

type (
	sessionSequenceModel interface {
		Insert(ctx context.Context, data *SessionSequence) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SessionSequence, error)
		Update(ctx context.Context, data *SessionSequence) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSessionSequenceModel struct {
		sqlc.CachedConn
		table string
	}

	SessionSequence struct {
		Id        int64 `db:"id"`
		SessionId int64 `db:"session_id"`
		MaxSeq    int64 `db:"max_seq"`
	}
)

func newSessionSequenceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSessionSequenceModel {
	return &defaultSessionSequenceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`session_sequence`",
	}
}

func (m *defaultSessionSequenceModel) Delete(ctx context.Context, id int64) error {
	sessionSequenceIdKey := fmt.Sprintf("%s%v", cacheSessionSequenceIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sessionSequenceIdKey)
	return err
}

func (m *defaultSessionSequenceModel) FindOne(ctx context.Context, id int64) (*SessionSequence, error) {
	sessionSequenceIdKey := fmt.Sprintf("%s%v", cacheSessionSequenceIdPrefix, id)
	var resp SessionSequence
	err := m.QueryRowCtx(ctx, &resp, sessionSequenceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionSequenceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionSequenceModel) Insert(ctx context.Context, data *SessionSequence) (sql.Result, error) {
	sessionSequenceIdKey := fmt.Sprintf("%s%v", cacheSessionSequenceIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sessionSequenceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SessionId, data.MaxSeq)
	}, sessionSequenceIdKey)
	return ret, err
}

func (m *defaultSessionSequenceModel) Update(ctx context.Context, data *SessionSequence) error {
	sessionSequenceIdKey := fmt.Sprintf("%s%v", cacheSessionSequenceIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sessionSequenceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SessionId, data.MaxSeq, data.Id)
	}, sessionSequenceIdKey)
	return err
}

func (m *defaultSessionSequenceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSessionSequenceIdPrefix, primary)
}

func (m *defaultSessionSequenceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionSequenceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSessionSequenceModel) tableName() string {
	return m.table
}
