// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package server

import (
	"context"

	"github.com/woxQAQ/im-service/internal/rpc/imrpc_message/internal/logic"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_message/internal/svc"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_message/pb"
)

type MsgServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMsgServer
}

func NewMsgServer(svcCtx *svc.ServiceContext) *MsgServer {
	return &MsgServer{
		svcCtx: svcCtx,
	}
}

func (s *MsgServer) SendMsg(ctx context.Context, in *pb.SendMessageReq) (*pb.SendMessageResp, error) {
	l := logic.NewSendMsgLogic(ctx, s.svcCtx)
	return l.SendMsg(in)
}
