// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package msg

import (
	"context"

	"github.com/woxQAQ/im-service/internal/rpc/imrpc_message/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	MsgData                = pb.MsgData
	PullMessageWithSeqReq  = pb.PullMessageWithSeqReq
	PullMessageWithSeqResp = pb.PullMessageWithSeqResp
	ResponseBase           = pb.ResponseBase
	SendMessageReq         = pb.SendMessageReq
	SendMessageResp        = pb.SendMessageResp

	Msg interface {
		SendMsg(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	}

	defaultMsg struct {
		cli zrpc.Client
	}
)

func NewMsg(cli zrpc.Client) Msg {
	return &defaultMsg{
		cli: cli,
	}
}

func (m *defaultMsg) SendMsg(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := pb.NewMsgClient(m.cli.Conn())
	return client.SendMsg(ctx, in, opts...)
}
