// Code generated by goctl. DO NOT EDIT.
// Source: id.proto

package id

import (
	"context"
	pb2 "github.com/woxQAQ/im-service/internal/app/id/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetSeqReq  = pb2.GetSeqReq
	GetSeqResp = pb2.GetSeqResp
	RespBase   = pb2.RespBase

	Id interface {
		GetSeq(ctx context.Context, in *GetSeqReq, opts ...grpc.CallOption) (*GetSeqResp, error)
	}

	defaultId struct {
		cli zrpc.Client
	}
)

func NewId(cli zrpc.Client) Id {
	return &defaultId{
		cli: cli,
	}
}

func (m *defaultId) GetSeq(ctx context.Context, in *GetSeqReq, opts ...grpc.CallOption) (*GetSeqResp, error) {
	client := pb2.NewIdClient(m.cli.Conn())
	return client.GetSeq(ctx, in, opts...)
}
