// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Validate string `json:"validate"`
}

type LoginResp struct {
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Gender   string `json:"gender"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id int64 `json:"id"`
}

type UserInfoResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Mobile string `json:"mobile"`
	Gender string `json:"gender"`
}
