// Code generated by goctl. DO NOT EDIT.
// Source: seq.proto

package seq

import (
	"context"

	"github.com/woxQAQ/im-service/internal/rpc/imrpc_seq/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetSeqRequest         = pb.GetSeqRequest
	GetSeqResponse        = pb.GetSeqResponse
	SetDefaultSeqRequest  = pb.SetDefaultSeqRequest
	SetDefaultSeqResponse = pb.SetDefaultSeqResponse

	Seq interface {
		GetSeq(ctx context.Context, in *GetSeqRequest, opts ...grpc.CallOption) (*GetSeqResponse, error)
		SetDefaultSeq(ctx context.Context, in *SetDefaultSeqRequest, opts ...grpc.CallOption) (*SetDefaultSeqResponse, error)
	}

	defaultSeq struct {
		cli zrpc.Client
	}
)

func NewSeq(cli zrpc.Client) Seq {
	return &defaultSeq{
		cli: cli,
	}
}

func (m *defaultSeq) GetSeq(ctx context.Context, in *GetSeqRequest, opts ...grpc.CallOption) (*GetSeqResponse, error) {
	client := pb.NewSeqClient(m.cli.Conn())
	return client.GetSeq(ctx, in, opts...)
}

func (m *defaultSeq) SetDefaultSeq(ctx context.Context, in *SetDefaultSeqRequest, opts ...grpc.CallOption) (*SetDefaultSeqResponse, error) {
	client := pb.NewSeqClient(m.cli.Conn())
	return client.SetDefaultSeq(ctx, in, opts...)
}
