// Code generated by goctl. DO NOT EDIT.
// Source: id.proto

package server

import (
	"context"
	"github.com/woxQAQ/im-service/internal/app/id/rpc/internal/logic"
	"github.com/woxQAQ/im-service/internal/app/id/rpc/internal/svc"
	pb2 "github.com/woxQAQ/im-service/internal/app/id/rpc/pb"
)

type IdServer struct {
	svcCtx *svc.ServiceContext
	pb2.UnimplementedIdServer
}

func NewIdServer(svcCtx *svc.ServiceContext) *IdServer {
	return &IdServer{
		svcCtx: svcCtx,
	}
}

func (s *IdServer) GetSeq(ctx context.Context, in *pb2.GetSeqReq) (*pb2.GetSeqResp, error) {
	l := logic.NewGetSeqLogic(ctx, s.svcCtx)
	return l.GetSeq(in)
}
