// Code generated by goctl. DO NOT EDIT.
// Source: seq.proto

package server

import (
	"context"

	"github.com/woxQAQ/im-service/internal/rpc/imrpc_seq/internal/logic"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_seq/internal/svc"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_seq/pb/pb"
)

type SeqServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSeqServer
}

func NewSeqServer(svcCtx *svc.ServiceContext) *SeqServer {
	return &SeqServer{
		svcCtx: svcCtx,
	}
}

func (s *SeqServer) GetSeq(ctx context.Context, in *pb.GetSeqRequest) (*pb.GetSeqResponse, error) {
	l := logic.NewGetSeqLogic(ctx, s.svcCtx)
	return l.GetSeq(in)
}

func (s *SeqServer) SetDefaultSeq(ctx context.Context, in *pb.SetDefaultSeqRequest) (*pb.SetDefaultSeqResponse, error) {
	l := logic.NewSetDefaultSeqLogic(ctx, s.svcCtx)
	return l.SetDefaultSeq(in)
}
