// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package server

import (
	"context"
	"github.com/woxQAQ/im-service/internal/rpc/msg/internal/logic"
	"github.com/woxQAQ/im-service/internal/rpc/msg/internal/svc"
	pb2 "github.com/woxQAQ/im-service/internal/rpc/msg/pb"
)

type MsgServer struct {
	svcCtx *svc.ServiceContext
	pb2.UnimplementedMsgServer
}

func NewMsgServer(svcCtx *svc.ServiceContext) *MsgServer {
	return &MsgServer{
		svcCtx: svcCtx,
	}
}

func (s *MsgServer) SendMsg(ctx context.Context, in *pb2.SendMessageReq) (*pb2.SendMessageResp, error) {
	l := logic.NewSendMsgLogic(ctx, s.svcCtx)
	return l.SendMsg(in)
}
