// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Method   int    `json:"method"` // mobile 0 and Email 1, more method can be supported further
	UserId   string `json:"userId"`
	Mobile   string `json:"mobile"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Validate string `json:"validate"`
}

type LoginResp struct {
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}

type ModifyRequest struct {
	Id     int64  `json:"Id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Mobile string `json:"mobile"`
	Gender string `json:"gender"`
}

type RegisterRequest struct {
	Method   int    `json:"method"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Gender   string `json:"gender"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id int64 `json:"Id"`
}

type UserInfoResp struct {
	Id     int64  `json:"Id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Mobile string `json:"mobile"`
	Gender string `json:"gender"`
}
