// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"github.com/woxQAQ/im-service/internal/rpc/imrpc_user/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest      = pb.LoginRequest
	LoginResp         = pb.LoginResp
	ModifyInfoRequest = pb.ModifyInfoRequest
	ModifyInfoResp    = pb.ModifyInfoResp
	RegisterRequest   = pb.RegisterRequest
	RegisterResp      = pb.RegisterResp
	UserInfoRequest   = pb.UserInfoRequest
	UserInfoResp      = pb.UserInfoResp

	User interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResp, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResp, error)
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResp, error)
		ModifyInfo(ctx context.Context, in *ModifyInfoRequest, opts ...grpc.CallOption) (*ModifyInfoResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

func (m *defaultUser) ModifyInfo(ctx context.Context, in *ModifyInfoRequest, opts ...grpc.CallOption) (*ModifyInfoResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.ModifyInfo(ctx, in, opts...)
}
