// Code generated by goctl. DO NOT EDIT.

package group

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupMsgFieldNames          = builder.RawFieldNames(&GroupMsg{})
	groupMsgRows                = strings.Join(groupMsgFieldNames, ",")
	groupMsgRowsExpectAutoSet   = strings.Join(stringx.Remove(groupMsgFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupMsgRowsWithPlaceHolder = strings.Join(stringx.Remove(groupMsgFieldNames, "`group_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGroupMsgGroupIdPrefix = "cache:groupMsg:groupId:"
)

type (
	groupMsgModel interface {
		Insert(ctx context.Context, data *GroupMsg) (sql.Result, error)
		FindOne(ctx context.Context, groupId int64) (*GroupMsg, error)
		Update(ctx context.Context, data *GroupMsg) error
		Delete(ctx context.Context, groupId int64) error
	}

	defaultGroupMsgModel struct {
		sqlc.CachedConn
		table string
	}

	GroupMsg struct {
		GroupId  int64          `db:"group_id"`
		SenderId sql.NullInt64  `db:"sender_id"`
		MsgId    sql.NullInt64  `db:"msg_id"`
		Time     sql.NullTime   `db:"time"`
		Content  sql.NullString `db:"content"`
	}
)

func newGroupMsgModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupMsgModel {
	return &defaultGroupMsgModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`group_msg`",
	}
}

func (m *defaultGroupMsgModel) Delete(ctx context.Context, groupId int64) error {
	groupMsgGroupIdKey := fmt.Sprintf("%s%v", cacheGroupMsgGroupIdPrefix, groupId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `group_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, groupId)
	}, groupMsgGroupIdKey)
	return err
}

func (m *defaultGroupMsgModel) FindOne(ctx context.Context, groupId int64) (*GroupMsg, error) {
	groupMsgGroupIdKey := fmt.Sprintf("%s%v", cacheGroupMsgGroupIdPrefix, groupId)
	var resp GroupMsg
	err := m.QueryRowCtx(ctx, &resp, groupMsgGroupIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? limit 1", groupMsgRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, groupId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMsgModel) Insert(ctx context.Context, data *GroupMsg) (sql.Result, error) {
	groupMsgGroupIdKey := fmt.Sprintf("%s%v", cacheGroupMsgGroupIdPrefix, data.GroupId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, groupMsgRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.SenderId, data.MsgId, data.Time, data.Content)
	}, groupMsgGroupIdKey)
	return ret, err
}

func (m *defaultGroupMsgModel) Update(ctx context.Context, data *GroupMsg) error {
	groupMsgGroupIdKey := fmt.Sprintf("%s%v", cacheGroupMsgGroupIdPrefix, data.GroupId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `group_id` = ?", m.table, groupMsgRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SenderId, data.MsgId, data.Time, data.Content, data.GroupId)
	}, groupMsgGroupIdKey)
	return err
}

func (m *defaultGroupMsgModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGroupMsgGroupIdPrefix, primary)
}

func (m *defaultGroupMsgModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `group_id` = ? limit 1", groupMsgRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupMsgModel) tableName() string {
	return m.table
}
