// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: seq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	// get session-space sequence id
	OperationType_OPERATION_TYPE_SESSION OperationType = 0
	// get group-session-space sequence id
	// equals with session
	OperationType_OPERATION_TYPE_GROUP OperationType = 1
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_SESSION",
		1: "OPERATION_TYPE_GROUP",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_SESSION": 0,
		"OPERATION_TYPE_GROUP":   1,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_seq_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_seq_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{0}
}

type RespBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	ErrDlt  string `protobuf:"bytes,3,opt,name=err_dlt,json=errDlt,proto3" json:"err_dlt,omitempty"`
}

func (x *RespBase) Reset() {
	*x = RespBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBase) ProtoMessage() {}

func (x *RespBase) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBase.ProtoReflect.Descriptor instead.
func (*RespBase) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{0}
}

func (x *RespBase) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RespBase) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *RespBase) GetErrDlt() string {
	if x != nil {
		return x.ErrDlt
	}
	return ""
}

type GetSessionIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId_1 int64 `protobuf:"varint,1,opt,name=user_id_1,json=userId1,proto3" json:"user_id_1,omitempty"`
	UserId_2 int64 `protobuf:"varint,2,opt,name=user_id_2,json=userId2,proto3" json:"user_id_2,omitempty"`
}

func (x *GetSessionIdRequest) Reset() {
	*x = GetSessionIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSessionIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionIdRequest) ProtoMessage() {}

func (x *GetSessionIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionIdRequest.ProtoReflect.Descriptor instead.
func (*GetSessionIdRequest) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionIdRequest) GetUserId_1() int64 {
	if x != nil {
		return x.UserId_1
	}
	return 0
}

func (x *GetSessionIdRequest) GetUserId_2() int64 {
	if x != nil {
		return x.UserId_2
	}
	return 0
}

type GetSeqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64         `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GroupId   int64         `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Type      OperationType `protobuf:"varint,4,opt,name=type,proto3,enum=seq.OperationType" json:"type,omitempty"`
}

func (x *GetSeqRequest) Reset() {
	*x = GetSeqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqRequest) ProtoMessage() {}

func (x *GetSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqRequest.ProtoReflect.Descriptor instead.
func (*GetSeqRequest) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{2}
}

func (x *GetSeqRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetSeqRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetSeqRequest) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_SESSION
}

type GetMessageIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GroupId   int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	BeginSeq  int64 `protobuf:"varint,3,opt,name=begin_seq,json=beginSeq,proto3" json:"begin_seq,omitempty"`
	EndSeq    int64 `protobuf:"varint,4,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`
}

func (x *GetMessageIdsRequest) Reset() {
	*x = GetMessageIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessageIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageIdsRequest) ProtoMessage() {}

func (x *GetMessageIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageIdsRequest.ProtoReflect.Descriptor instead.
func (*GetMessageIdsRequest) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessageIdsRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetMessageIdsRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetMessageIdsRequest) GetBeginSeq() int64 {
	if x != nil {
		return x.BeginSeq
	}
	return 0
}

func (x *GetMessageIdsRequest) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

type UpdateSessionSeqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GroupId   int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Step      int64 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *UpdateSessionSeqRequest) Reset() {
	*x = UpdateSessionSeqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSessionSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionSeqRequest) ProtoMessage() {}

func (x *UpdateSessionSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionSeqRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionSeqRequest) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSessionSeqRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *UpdateSessionSeqRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateSessionSeqRequest) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

type GetSessionIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base      *RespBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	SessionId int64     `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *GetSessionIdResponse) Reset() {
	*x = GetSessionIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSessionIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionIdResponse) ProtoMessage() {}

func (x *GetSessionIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionIdResponse.ProtoReflect.Descriptor instead.
func (*GetSessionIdResponse) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionIdResponse) GetBase() *RespBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetSessionIdResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type GetSeqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base   *RespBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CurSeq int64     `protobuf:"varint,2,opt,name=cur_seq,json=curSeq,proto3" json:"cur_seq,omitempty"`
	// int64 user_id = 3;
	//
	//	OperationType type = 4;
	//
	// int64 group_id = 5;
	MaxSeq int64 `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
}

func (x *GetSeqResponse) Reset() {
	*x = GetSeqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqResponse) ProtoMessage() {}

func (x *GetSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqResponse.ProtoReflect.Descriptor instead.
func (*GetSeqResponse) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{6}
}

func (x *GetSeqResponse) GetBase() *RespBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetSeqResponse) GetCurSeq() int64 {
	if x != nil {
		return x.CurSeq
	}
	return 0
}

func (x *GetSeqResponse) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type GetMessageIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId []int64   `protobuf:"varint,1,rep,packed,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Base      *RespBase `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *GetMessageIdsResponse) Reset() {
	*x = GetMessageIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessageIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageIdsResponse) ProtoMessage() {}

func (x *GetMessageIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageIdsResponse.ProtoReflect.Descriptor instead.
func (*GetMessageIdsResponse) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessageIdsResponse) GetMessageId() []int64 {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *GetMessageIdsResponse) GetBase() *RespBase {
	if x != nil {
		return x.Base
	}
	return nil
}

type UpdateSessionSeqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base      *RespBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	NewMaxSeq int64     `protobuf:"varint,2,opt,name=new_max_seq,json=newMaxSeq,proto3" json:"new_max_seq,omitempty"`
}

func (x *UpdateSessionSeqResponse) Reset() {
	*x = UpdateSessionSeqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSessionSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionSeqResponse) ProtoMessage() {}

func (x *UpdateSessionSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionSeqResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionSeqResponse) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSessionSeqResponse) GetBase() *RespBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UpdateSessionSeqResponse) GetNewMaxSeq() int64 {
	if x != nil {
		return x.NewMaxSeq
	}
	return 0
}

var File_seq_proto protoreflect.FileDescriptor

var file_seq_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x65, 0x71,
	0x22, 0x57, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x44, 0x6c, 0x74, 0x22, 0x4d, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x31, 0x12, 0x1a, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x22, 0x71, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x65,
	0x6e, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x6e,
	0x64, 0x53, 0x65, 0x71, 0x22, 0x67, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x22, 0x58, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x65, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x61, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x75, 0x72, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x75, 0x72, 0x53, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x65, 0x71,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x53, 0x65, 0x71, 0x22, 0x59,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x5d, 0x0a, 0x18, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f,
	0x6d, 0x61, 0x78, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e,
	0x65, 0x77, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x71, 0x2a, 0x45, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x50, 0x45,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x01, 0x32,
	0x9d, 0x02, 0x0a, 0x03, 0x53, 0x65, 0x71, 0x12, 0x43, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x12, 0x19, 0x2e,
	0x73, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x71, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x65, 0x71, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f,
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x71, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seq_proto_rawDescOnce sync.Once
	file_seq_proto_rawDescData = file_seq_proto_rawDesc
)

func file_seq_proto_rawDescGZIP() []byte {
	file_seq_proto_rawDescOnce.Do(func() {
		file_seq_proto_rawDescData = protoimpl.X.CompressGZIP(file_seq_proto_rawDescData)
	})
	return file_seq_proto_rawDescData
}

var file_seq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seq_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_seq_proto_goTypes = []interface{}{
	(OperationType)(0),               // 0: seq.OperationType
	(*RespBase)(nil),                 // 1: seq.RespBase
	(*GetSessionIdRequest)(nil),      // 2: seq.GetSessionIdRequest
	(*GetSeqRequest)(nil),            // 3: seq.GetSeqRequest
	(*GetMessageIdsRequest)(nil),     // 4: seq.GetMessageIdsRequest
	(*UpdateSessionSeqRequest)(nil),  // 5: seq.UpdateSessionSeqRequest
	(*GetSessionIdResponse)(nil),     // 6: seq.GetSessionIdResponse
	(*GetSeqResponse)(nil),           // 7: seq.GetSeqResponse
	(*GetMessageIdsResponse)(nil),    // 8: seq.GetMessageIdsResponse
	(*UpdateSessionSeqResponse)(nil), // 9: seq.UpdateSessionSeqResponse
}
var file_seq_proto_depIdxs = []int32{
	0, // 0: seq.GetSeqRequest.type:type_name -> seq.OperationType
	1, // 1: seq.GetSessionIdResponse.base:type_name -> seq.RespBase
	1, // 2: seq.GetSeqResponse.base:type_name -> seq.RespBase
	1, // 3: seq.GetMessageIdsResponse.base:type_name -> seq.RespBase
	1, // 4: seq.UpdateSessionSeqResponse.base:type_name -> seq.RespBase
	2, // 5: seq.Seq.GetSessionId:input_type -> seq.GetSessionIdRequest
	4, // 6: seq.Seq.GetMessageIds:input_type -> seq.GetMessageIdsRequest
	3, // 7: seq.Seq.GetSessionSeq:input_type -> seq.GetSeqRequest
	5, // 8: seq.Seq.UpdateSessionSeq:input_type -> seq.UpdateSessionSeqRequest
	6, // 9: seq.Seq.GetSessionId:output_type -> seq.GetSessionIdResponse
	8, // 10: seq.Seq.GetMessageIds:output_type -> seq.GetMessageIdsResponse
	7, // 11: seq.Seq.GetSessionSeq:output_type -> seq.GetSeqResponse
	9, // 12: seq.Seq.UpdateSessionSeq:output_type -> seq.UpdateSessionSeqResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_seq_proto_init() }
func file_seq_proto_init() {
	if File_seq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSessionIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessageIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSessionSeqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSessionIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessageIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSessionSeqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seq_proto_goTypes,
		DependencyIndexes: file_seq_proto_depIdxs,
		EnumInfos:         file_seq_proto_enumTypes,
		MessageInfos:      file_seq_proto_msgTypes,
	}.Build()
	File_seq_proto = out.File
	file_seq_proto_rawDesc = nil
	file_seq_proto_goTypes = nil
	file_seq_proto_depIdxs = nil
}
