// Code generated by goctl. DO NOT EDIT.
// Source: session.proto

package server

import (
	"context"

	"github.com/woxQAQ/im-service/internal/rpc/imrpc_session/internal/logic"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_session/internal/svc"
	"github.com/woxQAQ/im-service/internal/rpc/imrpc_session/pb/pb"
)

type SessionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSessionServer
}

func NewSessionServer(svcCtx *svc.ServiceContext) *SessionServer {
	return &SessionServer{
		svcCtx: svcCtx,
	}
}

func (s *SessionServer) InitSessionByUsersId(ctx context.Context, in *pb.InitSessionByUsersIdRequest) (*pb.InitSessionResponse, error) {
	l := logic.NewInitSessionByUsersIdLogic(ctx, s.svcCtx)
	return l.InitSessionByUsersId(in)
}

func (s *SessionServer) InitSessionByGroupId(ctx context.Context, in *pb.InitSessionByGroupIdRequest) (*pb.InitSessionResponse, error) {
	l := logic.NewInitSessionByGroupIdLogic(ctx, s.svcCtx)
	return l.InitSessionByGroupId(in)
}
