// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.8
// source: seq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	// get session-space sequence id
	OperationType_OPERATION_TYPE_SESSION OperationType = 0
	// get group-session-space sequence id
	// equals with session
	OperationType_OPERATION_TYPE_GID OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_SESSION",
		2: "OPERATION_TYPE_GID",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_SESSION": 0,
		"OPERATION_TYPE_GID":     2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_seq_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_seq_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{0}
}

type RespBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	ErrDlt  string `protobuf:"bytes,3,opt,name=err_dlt,json=errDlt,proto3" json:"err_dlt,omitempty"`
}

func (x *RespBase) Reset() {
	*x = RespBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBase) ProtoMessage() {}

func (x *RespBase) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBase.ProtoReflect.Descriptor instead.
func (*RespBase) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{0}
}

func (x *RespBase) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RespBase) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *RespBase) GetErrDlt() string {
	if x != nil {
		return x.ErrDlt
	}
	return ""
}

type GetSeqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId int64         `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type      OperationType `protobuf:"varint,2,opt,name=type,proto3,enum=seq.OperationType" json:"type,omitempty"`
}

func (x *GetSeqRequest) Reset() {
	*x = GetSeqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqRequest) ProtoMessage() {}

func (x *GetSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqRequest.ProtoReflect.Descriptor instead.
func (*GetSeqRequest) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeqRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GetSeqRequest) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_SESSION
}

type GetSeqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base   *RespBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CurSeq int64     `protobuf:"varint,2,opt,name=cur_seq,json=curSeq,proto3" json:"cur_seq,omitempty"`
	// int64 user_id = 3;
	Type OperationType `protobuf:"varint,4,opt,name=type,proto3,enum=seq.OperationType" json:"type,omitempty"`
}

func (x *GetSeqResponse) Reset() {
	*x = GetSeqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqResponse) ProtoMessage() {}

func (x *GetSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqResponse.ProtoReflect.Descriptor instead.
func (*GetSeqResponse) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{2}
}

func (x *GetSeqResponse) GetBase() *RespBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetSeqResponse) GetCurSeq() int64 {
	if x != nil {
		return x.CurSeq
	}
	return 0
}

func (x *GetSeqResponse) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_SESSION
}

var File_seq_proto protoreflect.FileDescriptor

var file_seq_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x65, 0x71,
	0x22, 0x57, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x44, 0x6c, 0x74, 0x22, 0x56, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x74, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x5f, 0x73, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x75, 0x72, 0x53, 0x65, 0x71, 0x12,
	0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x73, 0x65, 0x71, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x43, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x50, 0x45, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x49, 0x44, 0x10, 0x02, 0x32, 0x3f, 0x0a, 0x03,
	0x53, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x71, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seq_proto_rawDescOnce sync.Once
	file_seq_proto_rawDescData = file_seq_proto_rawDesc
)

func file_seq_proto_rawDescGZIP() []byte {
	file_seq_proto_rawDescOnce.Do(func() {
		file_seq_proto_rawDescData = protoimpl.X.CompressGZIP(file_seq_proto_rawDescData)
	})
	return file_seq_proto_rawDescData
}

var file_seq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seq_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_seq_proto_goTypes = []interface{}{
	(OperationType)(0),     // 0: seq.OperationType
	(*RespBase)(nil),       // 1: seq.RespBase
	(*GetSeqRequest)(nil),  // 2: seq.GetSeqRequest
	(*GetSeqResponse)(nil), // 3: seq.GetSeqResponse
}
var file_seq_proto_depIdxs = []int32{
	0, // 0: seq.GetSeqRequest.type:type_name -> seq.OperationType
	1, // 1: seq.GetSeqResponse.base:type_name -> seq.RespBase
	0, // 2: seq.GetSeqResponse.type:type_name -> seq.OperationType
	2, // 3: seq.Seq.GetSessionSeq:input_type -> seq.GetSeqRequest
	3, // 4: seq.Seq.GetSessionSeq:output_type -> seq.GetSeqResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_seq_proto_init() }
func file_seq_proto_init() {
	if File_seq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seq_proto_goTypes,
		DependencyIndexes: file_seq_proto_depIdxs,
		EnumInfos:         file_seq_proto_enumTypes,
		MessageInfos:      file_seq_proto_msgTypes,
	}.Build()
	File_seq_proto = out.File
	file_seq_proto_rawDesc = nil
	file_seq_proto_goTypes = nil
	file_seq_proto_depIdxs = nil
}
