// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.8
// source: seq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSeqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetSeqRequest) Reset() {
	*x = GetSeqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqRequest) ProtoMessage() {}

func (x *GetSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqRequest.ProtoReflect.Descriptor instead.
func (*GetSeqRequest) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeqRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSeqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	CurSeq  uint32 `protobuf:"varint,3,opt,name=cur_seq,json=curSeq,proto3" json:"cur_seq,omitempty"`
	MaxSeq  uint32 `protobuf:"varint,4,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
}

func (x *GetSeqResponse) Reset() {
	*x = GetSeqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeqResponse) ProtoMessage() {}

func (x *GetSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeqResponse.ProtoReflect.Descriptor instead.
func (*GetSeqResponse) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeqResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GetSeqResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetSeqResponse) GetCurSeq() uint32 {
	if x != nil {
		return x.CurSeq
	}
	return 0
}

func (x *GetSeqResponse) GetMaxSeq() uint32 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type SetDefaultSeqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *SetDefaultSeqRequest) Reset() {
	*x = SetDefaultSeqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultSeqRequest) ProtoMessage() {}

func (x *SetDefaultSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultSeqRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultSeqRequest) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{2}
}

func (x *SetDefaultSeqRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SetDefaultSeqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurSeq  string `protobuf:"bytes,1,opt,name=cur_seq,json=curSeq,proto3" json:"cur_seq,omitempty"`
	ErrCode int32  `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *SetDefaultSeqResponse) Reset() {
	*x = SetDefaultSeqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultSeqResponse) ProtoMessage() {}

func (x *SetDefaultSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultSeqResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultSeqResponse) Descriptor() ([]byte, []int) {
	return file_seq_proto_rawDescGZIP(), []int{3}
}

func (x *SetDefaultSeqResponse) GetCurSeq() string {
	if x != nil {
		return x.CurSeq
	}
	return ""
}

func (x *SetDefaultSeqResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *SetDefaultSeqResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_seq_proto protoreflect.FileDescriptor

var file_seq_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x65, 0x71,
	0x22, 0x28, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x63, 0x75, 0x72, 0x53, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x53,
	0x65, 0x71, 0x22, 0x2f, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x75, 0x72, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x75, 0x72, 0x53, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x32, 0x80, 0x01, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x12, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x12, 0x12, 0x2e, 0x73, 0x65,
	0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x53, 0x65, 0x71, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x53, 0x65, 0x74, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x73, 0x65, 0x71, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seq_proto_rawDescOnce sync.Once
	file_seq_proto_rawDescData = file_seq_proto_rawDesc
)

func file_seq_proto_rawDescGZIP() []byte {
	file_seq_proto_rawDescOnce.Do(func() {
		file_seq_proto_rawDescData = protoimpl.X.CompressGZIP(file_seq_proto_rawDescData)
	})
	return file_seq_proto_rawDescData
}

var file_seq_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_seq_proto_goTypes = []interface{}{
	(*GetSeqRequest)(nil),         // 0: seq.GetSeqRequest
	(*GetSeqResponse)(nil),        // 1: seq.GetSeqResponse
	(*SetDefaultSeqRequest)(nil),  // 2: seq.SetDefaultSeqRequest
	(*SetDefaultSeqResponse)(nil), // 3: seq.SetDefaultSeqResponse
}
var file_seq_proto_depIdxs = []int32{
	0, // 0: seq.seq.GetSeq:input_type -> seq.GetSeqRequest
	2, // 1: seq.seq.SetDefaultSeq:input_type -> seq.SetDefaultSeqRequest
	1, // 2: seq.seq.GetSeq:output_type -> seq.GetSeqResponse
	3, // 3: seq.seq.SetDefaultSeq:output_type -> seq.SetDefaultSeqResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seq_proto_init() }
func file_seq_proto_init() {
	if File_seq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultSeqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultSeqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seq_proto_goTypes,
		DependencyIndexes: file_seq_proto_depIdxs,
		MessageInfos:      file_seq_proto_msgTypes,
	}.Build()
	File_seq_proto = out.File
	file_seq_proto_rawDesc = nil
	file_seq_proto_goTypes = nil
	file_seq_proto_depIdxs = nil
}
