// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: seq.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Seq_GetSeq_FullMethodName        = "/seq.seq/GetSeq"
	Seq_SetDefaultSeq_FullMethodName = "/seq.seq/SetDefaultSeq"
)

// SeqClient is the client API for Seq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeqClient interface {
	GetSeq(ctx context.Context, in *GetSeqRequest, opts ...grpc.CallOption) (*GetSeqResponse, error)
	SetDefaultSeq(ctx context.Context, in *SetDefaultSeqRequest, opts ...grpc.CallOption) (*SetDefaultSeqResponse, error)
}

type seqClient struct {
	cc grpc.ClientConnInterface
}

func NewSeqClient(cc grpc.ClientConnInterface) SeqClient {
	return &seqClient{cc}
}

func (c *seqClient) GetSeq(ctx context.Context, in *GetSeqRequest, opts ...grpc.CallOption) (*GetSeqResponse, error) {
	out := new(GetSeqResponse)
	err := c.cc.Invoke(ctx, Seq_GetSeq_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seqClient) SetDefaultSeq(ctx context.Context, in *SetDefaultSeqRequest, opts ...grpc.CallOption) (*SetDefaultSeqResponse, error) {
	out := new(SetDefaultSeqResponse)
	err := c.cc.Invoke(ctx, Seq_SetDefaultSeq_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeqServer is the server API for Seq service.
// All implementations must embed UnimplementedSeqServer
// for forward compatibility
type SeqServer interface {
	GetSeq(context.Context, *GetSeqRequest) (*GetSeqResponse, error)
	SetDefaultSeq(context.Context, *SetDefaultSeqRequest) (*SetDefaultSeqResponse, error)
	mustEmbedUnimplementedSeqServer()
}

// UnimplementedSeqServer must be embedded to have forward compatible implementations.
type UnimplementedSeqServer struct {
}

func (UnimplementedSeqServer) GetSeq(context.Context, *GetSeqRequest) (*GetSeqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeq not implemented")
}
func (UnimplementedSeqServer) SetDefaultSeq(context.Context, *SetDefaultSeqRequest) (*SetDefaultSeqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultSeq not implemented")
}
func (UnimplementedSeqServer) mustEmbedUnimplementedSeqServer() {}

// UnsafeSeqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeqServer will
// result in compilation errors.
type UnsafeSeqServer interface {
	mustEmbedUnimplementedSeqServer()
}

func RegisterSeqServer(s grpc.ServiceRegistrar, srv SeqServer) {
	s.RegisterService(&Seq_ServiceDesc, srv)
}

func _Seq_GetSeq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeqServer).GetSeq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seq_GetSeq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeqServer).GetSeq(ctx, req.(*GetSeqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seq_SetDefaultSeq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultSeqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeqServer).SetDefaultSeq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Seq_SetDefaultSeq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeqServer).SetDefaultSeq(ctx, req.(*SetDefaultSeqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Seq_ServiceDesc is the grpc.ServiceDesc for Seq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Seq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seq.seq",
	HandlerType: (*SeqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeq",
			Handler:    _Seq_GetSeq_Handler,
		},
		{
			MethodName: "SetDefaultSeq",
			Handler:    _Seq_SetDefaultSeq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seq.proto",
}
